### ISSUE TITLE
Tools - touch does not update timestamp

### ISSUE THREAD

**Issue by twoinke** [Steckschwein/code#24]
currently touch does not modify the timestamp (WrtDate,WrtTime) of an existing file

[Issue created by mlauke: 2017-10-06]
[Last updated on bitbucket: 2018-04-27]

**Comment by mlauke** [comment]
![image](https://github.com/Steckschwein/code/assets/4578883/63b2aa68-f011-46e4-a44f-29836c4fc51c)
