### ISSUE TITLE
FAT32 - implement fread()/fseek()

### ISSUE THREAD

**Issue by twoinke** [Steckschwein/code#41]
**tasks**

*  save seek position after each (block) read +$0200
*  calculate cluster number and lba from seek position
*  implement fread() 
    * take care of current seek position
    * use copy strategy to enable read for various sizes - not only reads in multiples of block size
    * update seek position

[Issue created by mlauke: 2018-07-08]
[Last updated on bitbucket: 2021-09-05]

[Comment created by mlauke: 2021-09-05]
ref #41
+clean code
+revision write

→ <<cset 9c53d2282123>>

[Comment created by mlauke: 2021-09-04]
ref #41
+enhance cmp32

→ <<cset 9655866aea42>>

[Comment created by mlauke: 2021-09-04]
ref #41
+fix tools

→ <<cset ae98fb911302>>

[Comment created by mlauke: 2021-09-04]
ref #41
+fix byte read, more tests
+refactor exec()

→ <<cset f59c17328e1e>>

[Comment created by mlauke: 2021-09-04]
ref #41
+revision read block/byte
+more tests

→ <<cset ee6d9ee6d5d4>>

[Comment created by mlauke: 2021-09-04]
ref #41
+update

→ <<cset 29d402073cc3>>

[Comment created by mlauke: 2021-09-04]
ref #41
+some macros

→ <<cset 7d911866eb16>>

[Comment created by mlauke: 2021-09-04]
ref #41
+revision test
+poor read byte impl

→ <<cset 79b8f4e688be>>

[Comment created by mlauke: 2021-09-04]
ref #41
+fix tests and mock

→ <<cset e80ddadc301e>>

[Comment created by mlauke: 2021-09-04]
ref #41
+fix asmunit
+enhance with stack corruptuon detection

→ <<cset bc92277a9696>>

[Comment created by mlauke: 2021-09-04]
ref #41
+update

→ <<cset e98ded34ccfe>>

[Comment created by mlauke: 2021-09-04]
ref #41
+update

→ <<cset 067e5dae5482>>

[Comment created by mlauke: 2021-09-04]
ref #41
+clean

→ <<cset f2a22ccdcb83>>

[Comment created by mlauke: 2021-09-04]
ref #41
+clean

→ <<cset 47668a0e87b7>>

[Comment created by mlauke: 2021-09-04]
ref #41
+revision

→ <<cset 647cf61a6283>>

[Comment created by mlauke: 2021-09-03]
Merged in issues/41 (pull request #1)

Issues/41

* ref #41
+update

* ref #41
+fix asmunit
+enhance with stack corruptuon detection

* ref #41
+fix tests and mock

* ref #41
+revision test
+poor read byte impl

* ref #41
+some macros

* ref #41
+update

* ref #41
+revision read block/byte
+more tests

* ref #41
+fix byte read, more tests
+refactor exec()

* ref #41
+fix tools

* +rm

Approved-by: Thomas Woinke

→ <<cset ae52740097e3>>

[Comment created by mlauke: 2021-09-03]
Merged in issues/41 (pull request #1)

Issues/41

* ref #41
+update

* ref #41
+fix asmunit
+enhance with stack corruptuon detection

* ref #41
+fix tests and mock

* ref #41
+revision test
+poor read byte impl

* ref #41
+some macros

* ref #41
+update

* ref #41
+revision read block/byte
+more tests

* ref #41
+fix byte read, more tests
+refactor exec()

* ref #41
+fix tools

* +rm

Approved-by: Thomas Woinke

→ <<cset ae52740097e3>>

[Comment created by mlauke: 2021-09-03]
Merged in issues/41 (pull request #1)

Issues/41

* ref #41
+update

* ref #41
+fix asmunit
+enhance with stack corruptuon detection

* ref #41
+fix tests and mock

* ref #41
+revision test
+poor read byte impl

* ref #41
+some macros

* ref #41
+update

* ref #41
+revision read block/byte
+more tests

* ref #41
+fix byte read, more tests
+refactor exec()

* ref #41
+fix tools

* +rm

Approved-by: Thomas Woinke

→ <<cset ae52740097e3>>

[Comment created by mlauke: 2021-09-03]
Merged in issues/41 (pull request #1)

Issues/41

* ref #41
+update

* ref #41
+fix asmunit
+enhance with stack corruptuon detection

* ref #41
+fix tests and mock

* ref #41
+revision test
+poor read byte impl

* ref #41
+some macros

* ref #41
+update

* ref #41
+revision read block/byte
+more tests

* ref #41
+fix byte read, more tests
+refactor exec()

* ref #41
+fix tools

* +rm

Approved-by: Thomas Woinke

→ <<cset ae52740097e3>>

[Comment created by mlauke: 2021-09-03]
Merged in issues/41 (pull request #1)

Issues/41

* ref #41
+update

* ref #41
+fix asmunit
+enhance with stack corruptuon detection

* ref #41
+fix tests and mock

* ref #41
+revision test
+poor read byte impl

* ref #41
+some macros

* ref #41
+update

* ref #41
+revision read block/byte
+more tests

* ref #41
+fix byte read, more tests
+refactor exec()

* ref #41
+fix tools

* +rm

Approved-by: Thomas Woinke

→ <<cset ae52740097e3>>

[Comment created by mlauke: 2021-09-03]
Merged in issues/41 (pull request #1)

Issues/41

* ref #41
+update

* ref #41
+fix asmunit
+enhance with stack corruptuon detection

* ref #41
+fix tests and mock

* ref #41
+revision test
+poor read byte impl

* ref #41
+some macros

* ref #41
+update

* ref #41
+revision read block/byte
+more tests

* ref #41
+fix byte read, more tests
+refactor exec()

* ref #41
+fix tools

* +rm

Approved-by: Thomas Woinke

→ <<cset ae52740097e3>>

[Comment created by mlauke: 2021-09-03]
Merged in issues/41 (pull request #1)

Issues/41

* ref #41
+update

* ref #41
+fix asmunit
+enhance with stack corruptuon detection

* ref #41
+fix tests and mock

* ref #41
+revision test
+poor read byte impl

* ref #41
+some macros

* ref #41
+update

* ref #41
+revision read block/byte
+more tests

* ref #41
+fix byte read, more tests
+refactor exec()

* ref #41
+fix tools

* +rm

Approved-by: Thomas Woinke

→ <<cset ae52740097e3>>

[Comment created by mlauke: 2021-09-03]
Merged in issues/41 (pull request #1)

Issues/41

* ref #41
+update

* ref #41
+fix asmunit
+enhance with stack corruptuon detection

* ref #41
+fix tests and mock

* ref #41
+revision test
+poor read byte impl

* ref #41
+some macros

* ref #41
+update

* ref #41
+revision read block/byte
+more tests

* ref #41
+fix byte read, more tests
+refactor exec()

* ref #41
+fix tools

* +rm

Approved-by: Thomas Woinke

→ <<cset ae52740097e3>>

[Comment created by mlauke: 2021-09-03]
Merged in issues/41 (pull request #1)

Issues/41

* ref #41
+update

* ref #41
+fix asmunit
+enhance with stack corruptuon detection

* ref #41
+fix tests and mock

* ref #41
+revision test
+poor read byte impl

* ref #41
+some macros

* ref #41
+update

* ref #41
+revision read block/byte
+more tests

* ref #41
+fix byte read, more tests
+refactor exec()

* ref #41
+fix tools

* +rm

Approved-by: Thomas Woinke

→ <<cset ae52740097e3>>

[Comment created by mlauke: 2021-09-02]
ref #41
+fix tools

→ <<cset ae98fb911302>>

[Comment created by mlauke: 2021-09-02]
ref #41
+fix byte read, more tests
+refactor exec()

→ <<cset f59c17328e1e>>

[Comment created by mlauke: 2021-08-31]
ref #41
+revision read block/byte
+more tests

→ <<cset ee6d9ee6d5d4>>

[Comment created by mlauke: 2021-08-23]
ref #41
+update

→ <<cset 29d402073cc3>>

[Comment created by mlauke: 2021-08-05]
ref #41
+some macros

→ <<cset 7d911866eb16>>

[Comment created by mlauke: 2021-07-21]
ref #41
+revision test
+poor read byte impl

→ <<cset 79b8f4e688be>>

[Comment created by mlauke: 2021-07-20]
ref #41
+fix tests and mock

→ <<cset e80ddadc301e>>

[Comment created by mlauke: 2021-07-20]
ref #41
+fix asmunit
+enhance with stack corruptuon detection

→ <<cset bc92277a9696>>

[Comment created by mlauke: 2021-07-19]
ref #41
+update

→ <<cset e98ded34ccfe>>

[Comment created by mlauke: 2021-07-18]
ref #41
+update

→ <<cset 067e5dae5482>>

[Comment created by mlauke: 2021-07-17]
ref #41
+clean

→ <<cset f2a22ccdcb83>>

[Comment created by mlauke: 2021-07-17]
ref #41
+clean

→ <<cset 47668a0e87b7>>

[Comment created by mlauke: 2021-07-16]
ref #41
+revision

→ <<cset 647cf61a6283>>

[Comment created by mlauke: 2018-10-09]
ref #41
+fix cluster chain and select

→ <<cset 0a9dfdadea8e>>

[Comment created by mlauke: 2018-10-09]
ref #41
+update

→ <<cset 2f8a5bd5bf8b>>

[Comment created by mlauke: 2018-10-09]
ref #41
+disable test

→ <<cset 89e35aa50165>>

[Comment created by mlauke: 2018-10-09]
ref #41
+fat32 cl chain
+ppmview app with tests

→ <<cset 56eb0d16ae76>>

[Comment created by mlauke: 2018-10-05]
ref #41
+enh. test facility, output test name

→ <<cset 9560870286a2>>

[Comment created by mlauke: 2018-10-05]
ref #41
+more tests

→ <<cset 9a8578dee9ef>>

[Comment created by mlauke: 2018-10-05]
ref #41
+more tests, add mocks

→ <<cset e7994dc6c2f1>>

[Comment created by mlauke: 2018-10-03]
ref #41
+more tests

→ <<cset 10fa854602d5>>

[Comment created by mlauke: 2018-10-03]
ref #41
+thoughts

→ <<cset a5f30bd612b7>>

[Comment created by mlauke: 2018-07-08]
ref #41
+revision fread/fseek api

→ <<cset 1697e3eb5a56>>

**Comment by mlauke** [comment]
use test_fat32_seek.s to get an idea how things work on asm level...
