### ISSUE TITLE
FAT32: enhance kernel api with fat_write_byte

### ISSUE THREAD

**Issue by twoinke** [Steckschwein/code#48]
implement fat\_write\_byte for single byte write, return code is C=0 succes, C=1 error

‌

[Issue created by mlauke: 2021-10-29]
[Last updated on bitbucket: 2022-08-25]

[Comment created by mlauke: 2022-08-25]
ref #48
+update

→ <<cset d68030c28cb5>>

[Comment created by mlauke: 2022-07-17]
ref #48
+clean code
+volumeId struct

→ <<cset 9392850e1f8c>>

[Comment created by mlauke: 2022-07-07]
ref #48
+fix zp locations
+clean code

→ <<cset 26c3e82174f6>>

[Comment created by mlauke: 2022-07-05]
ref #48
+clean code

→ <<cset 888b0aa6c142>>

[Comment created by mlauke: 2022-07-04]
ref #48
+update read, clean code

→ <<cset a3d8b2fbc0f4>>

[Comment created by mlauke: 2022-06-02]
ref #48
+update

→ <<cset 39aa7b918daf>>

[Comment created by mlauke: 2022-05-29]
ref #48
+impr. code

→ <<cset 5d9990d41d8d>>

[Comment created by mlauke: 2022-05-29]
ref #48
+reserve cl
+update dir entry
+test

→ <<cset d112785000e6>>

[Comment created by mlauke: 2022-05-29]
ref #48
+improve dir lba, entry pos calc

→ <<cset a3e6e96d9345>>

[Comment created by mlauke: 2022-05-28]
ref #48
+impl. byte write, tests

→ <<cset b6ca1d56dcbc>>

[Comment created by mlauke: 2022-05-21]
ref #48
+update

→ <<cset 67cae08e0027>>

[Comment created by mlauke: 2021-10-29]
ref #48
+initial

→ <<cset a23be0009623>>

**Comment by mlauke** [comment]
check out test_fat32_write.s to get an idea how to use the write byte api. krn_write_byte is just a "wrapper" around it.
