### ISSUE TITLE
SPI: read/write must be wrapped as critical section

### ISSUE THREAD

**Issue by twoinke** [Steckschwein/code#52]
* spi read/write must be implemented as critical sections
* keyboard irq acknowledge is not possible if spi device is busy \(e.g. sdcard selected\) which lead to “endless keyboard irqs”

    * the spi\_select\_device/spi\_deselect\_device should be “stacked”
    * 
    

steps to reproduce:

* steck shell enter ll to list files in directory \(should be long enough\)
* $ ll 
* at the same time ll is running, hit various keys multiple times

‌

[Issue created by mlauke: 2023-02-13]
[Last updated on bitbucket: 2023-03-25]

[Comment created by mlauke: 2023-03-25]
ref #52
+fix edlply read
+fix sd error handling

→ <<cset d3c725b29f6a>>

[Comment created by mlauke: 2023-03-25]
ref #52
+fix spi_read
+impr. sd wait

→ <<cset 52ca9a996b25>>

[Comment created by mlauke: 2023-03-19]
ref #52
+relocatable

→ <<cset 8f37a78710c9>>

[Comment created by mlauke: 2023-03-19]
ref #52
+old ram layout, kernel at $e800

→ <<cset 593d9557041f>>

[Comment created by mlauke: 2023-03-19]
ref #52
+disable kb irq, impr. code

→ <<cset 4e3221aa4fb6>>

[Comment created by mlauke: 2023-03-14]
ref #52
+clean code, irq handler

→ <<cset 49570c53b8d5>>

[Comment created by mlauke: 2023-03-01]
ref #52
+revision, clean code
+disable keyboard irq

→ <<cset 5029c1c112b2>>

[Comment created by mlauke: 2023-02-13]
ref #52
+spi critical section

→ <<cset 056619fc4efd>>

**Comment by mlauke** [comment]
@twoinke not a bug, since we do not use keyboard IRQs anymore. the keys are fetched by the host (poll)
